### ISSUE TITLE
Ticking LavaSplashParticle causes java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by tahosa** [bottomtextdanny/Effective-Forge-#11]
When running on a server, lava particles cause a client crash. Multiple people on my server report this exact issue, and it primarily arises when there are lots of particles caused by lava flow updates.

Java version: Adoptium 17.0.2
Minecraft Version: 1.18.1
Mod Version: effective_for_forge-1.001

Example crash report: https://pastebin.com/9hcxDxYq

**Comment by bottomtextdanny** [comment]
should work on servers with latest versions of the mod, 1.18.1 is not really supported anymore though
