### ISSUE TITLE
Update Demand for 1.18.2

### ISSUE THREAD

**Issue by ProoTURK** [bottomtextdanny/Effective-Forge-#12]
Pls do it

**Comment by evanbones** [comment]
Stop. It's people like you that give the modding community a bad name. You are not entitled to anything, especially not from a mod developer working for FREE. You are in no place to demand ANYTHING.

The mod has been updated to 1.18.2 as of the latest release.

**Comment by bottomtextdanny** [comment]
it is for 1.18.2
