### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by MattB70** [bottomtextdanny/Effective-Forge-#17]
Server crashes on startup, alternatively you can join the server if it does not have the mod, but jumping in water causes the client to crash to the menu.

Server crash on startup log:
https://gist.github.com/MattB70/3fa0e914f69c598200643395c9425568

**Comment by VirtualGaming1** [comment]
+1 on this

**Comment by FullMetalMaster** [comment]
it wont get fixed most likely

**Comment by bottomtextdanny** [comment]
try new version for 1.18.2

**Comment by bottomtextdanny** [comment]
cant reproduce with newest versions of the mod, if theres is any related problem please open a new issue
