### ISSUE TITLE
Immediate crash when joining multiplayer session

### ISSUE THREAD

**Issue by ghost** [bottomtextdanny/Effective-Forge-#18]
Forge & Forge Server version: 40.1.52
Minecraft version: 1.18.2

Upon testing the mod independently in a forge server with no mods loaded, Minecraft crashes completely. Crash logs says a ticking entity occurs. To repeat, no other mods were loaded and only effective was loaded and I had only join a forge server with no mods loaded either.

Crash report: https://gist.github.com/DannyLeWasTaken/24de4cced726d3330ba6bc4582d1ea4d
Logs: https://gist.github.com/DannyLeWasTaken/12d0d2ec9998ef5c012cf8269697cf1a

**Comment by ThatGuyJess** [comment]
Just typing this to say I'm having the same issue 👍

**Comment by dthelegend** [comment]
I can confirm that I too have experienced this issue

**Comment by Jusey1** [comment]
Can confirm, same crash. It seems like the mod is in a state where it is needed on the server side to work properly but it crashes the server due to loading client only elements. There's no way around this. The mod cannot work online.

**Comment by jochuan** [comment]
Same crash for me too

**Comment by IsaakHlr** [comment]
I'm having the same ticking entity crash on my server. I have tested and confirmed it is Effective causing the crash. I notice it especially near Villages & Pillagers, but may be a coincidence. Looking forward to a fix :-)

**Comment by Camawama** [comment]
Found out that whenever an entity touches water and the Effective effects start to play, it crashes the server.

**Comment by V972** [comment]
Same here with the same particle

**Comment by Jusey1** [comment]
This mod still crashes btw even with the newest 1.18.2 version...

**Comment by bottomtextdanny** [comment]
cant reproduce with newest versions of the mod, if theres is any related problem please open a new issue
