### ISSUE TITLE
Splashes Inconsistent 

### ISSUE THREAD

**Issue by GamerGaven** [bottomtextdanny/Effective-Forge-#2]
From the small amount of testing I did, the splashes seem to never properly work when another entity is nearby when it hits the water. The last ravager summoned made a smaller splash than expected as well? I did test it a second time isolated from any other mods and it still happened using the latest forge version and latest version of this mod as well. Thanks for making a port btw, its tough deciding between forge and fabric. 
Landing in water one block deep seems to cause the same effect as well. 

https://user-images.githubusercontent.com/83141599/146983780-e15afa88-35df-4959-af5b-7db6d96a170a.mp4

**Comment by bottomtextdanny** [comment]
try version 1.2.2

**Comment by bottomtextdanny** [comment]
this shouldnt happen with newest versions
