### ISSUE TITLE
Crash on server after 1-2 minutes

### ISSUE THREAD

**Issue by attHD** [bottomtextdanny/Effective-Forge-#3]

**Comment by attHD** [comment]
Error: java.lang.NullPointerException: Registry Object not present: effective_fg:droplet
Exit Code: -1

**Comment by attHD** [comment]
I just walked around the spawnpoint waiting for my friends to join and the game crashed after 1-2 minutes. The mod was only on the client side. And just me on the server

**Comment by SeffInSpace** [comment]
same thing is happening to me!

**Comment by RobAmaral** [comment]
the same thing happening to me, but in my case it's instant when joining the server

**Comment by Nublys** [comment]
Hey, Hey! Same here.

**Comment by Lucaspec72** [comment]
Same, crashed for me right after connecting.

**Comment by Spielepapagei** [comment]
Same to me _only in Multiplayer_.

java.lang.NullPointerException: Registry Object not present: effective_fg:droplet

[crash-2022-04-01_14.23.10-client.txt](https://github.com/bottomtextdanny/Effective-Forge-/files/8397612/crash-2022-04-01_14.23.10-client.txt)

**Comment by WarmIceCream** [comment]
even the 1.18.2 version still has this issue on servers...

**Comment by bottomtextdanny** [comment]
check if it works with version 1.2.2

**Comment by bottomtextdanny** [comment]
cant reproduce with newest versions of the mod, if theres is any related problem please open a new issue
