### ISSUE TITLE
Abnormal splash 

### ISSUE THREAD

**Issue by Dr-WeiAL** [bottomtextdanny/Effective-Forge-#4]
There will be no spray when the entity falls into the water from a very high place 

Player, creeper, iron golem, ravager have all tried

**Comment by PercyJames** [comment]
same for me

**Comment by bottomtextdanny** [comment]
this cant be fixed easily sorry, if the movement of an entity gets cutted by block collision before the splash is processed then it will be corresponding to the new motion

**Comment by bottomtextdanny** [comment]
i guess i wont fix that, original mod doesnt provide a solution either
