### ISSUE TITLE
Not Actually Client Side?

### ISSUE THREAD

**Issue by cosvoyage** [bottomtextdanny/Effective-Forge-#6]
My server didn't let anyone who didn't have effective in, and now that I've removed it from the server, it won't let anyone who has it in.

**Comment by efffauw** [comment]
its due to a limitation in Forge

**Comment by bottomtextdanny** [comment]
try with version 1.2.2

**Comment by bottomtextdanny** [comment]
should work in servers now. theres no support for minecraft 1.18.1 sorry if you still play that version!
