### ISSUE TITLE
causes mc 1.18.2/forge 40.0.31 to crash

### ISSUE THREAD

**Issue by amazingakita** [bottomtextdanny/Effective-Forge-#8]
trying to boot up minecraft 1.18.2 with this mod in the mods folder causes the following error: 
`org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)`

[crash-2022-03-26_08.38.09-client.txt](https://github.com/bottomtextdanny/Effective-Forge-/files/8355017/crash-2022-03-26_08.38.09-client.txt)

**Comment by ProoTURK** [comment]
it happens because this mod doesnt supports 1.18.2 yet

**Comment by bottomtextdanny** [comment]
it does now!
